package moiss.oracle.apps.fnd.moiss.server;


import moiss.oracle.apps.fnd.moiss.lov.server.popPunchLOVVOImpl;

import oracle.apps.fnd.framework.OAViewObject;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MoissPunchAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public MoissPunchAMImpl() {
    }


    public void createRecord(String voname)
    {
      System.out.println((new StringBuilder()).append("Name of First VO1").append(voname).toString());
        OAViewObject vo = (OAViewObject)findViewObject(voname);
        System.out.println(vo);
        if(!vo.isPreparedForExecution())
        {
            vo.executeQuery();
        }
        Row row = vo.createRow();
        vo.insertRow(row);
        row.setNewRowState((byte)-1);
        System.out.println("New Row has been created");
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("moiss.oracle.apps.fnd.moiss.server", /* package name */
      "MoissPunchAMLocal" /* Configuration Name */);
    }
    public void apply()  
    {  
     getTransaction().commit();  
     System.out.println("Apply value Commited");
    }


    /**Container's getter for MoissCIOVO
     */
    public MoissCIOVOImpl getMoissCIOVO() {
        return (MoissCIOVOImpl)findViewObject("MoissCIOVO");
    }


    /**Container's getter for MoissPInfoVO
     */
    public MoissPInfoVOImpl getMoissPInfoVO() {
        return (MoissPInfoVOImpl)findViewObject("MoissPInfoVO");
    }

    /**Container's getter for MoissPInfoVO2
     */
    public MoissPInfoVOImpl getMoissPInfoVO2() {
        return (MoissPInfoVOImpl)findViewObject("MoissPInfoVO2");
    }

    /**Container's getter for MoissPInfoVO1
     */
    public MoissPInfoVOImpl getMoissPInfoVO1() {
        return (MoissPInfoVOImpl)findViewObject("MoissPInfoVO1");
    }

    /**Container's getter for MoissPInfoVO3
     */
    public MoissPInfoVOImpl getMoissPInfoVO3() {
        return (MoissPInfoVOImpl)findViewObject("MoissPInfoVO3");
    }

    /**Container's getter for MoissPInfoVO4
     */
    public MoissPInfoVOImpl getMoissPInfoVO4() {
        return (MoissPInfoVOImpl)findViewObject("MoissPInfoVO4");
    }

    /**Container's getter for MoissPInfoVO5
     */
    public MoissPInfoVOImpl getMoissPInfoVO5() {
        return (MoissPInfoVOImpl)findViewObject("MoissPInfoVO5");
    }

    /**Container's getter for MoissPInfoVO6
     */
    public MoissPInfoVOImpl getMoissPInfoVO6() {
        return (MoissPInfoVOImpl)findViewObject("MoissPInfoVO6");
    }

    /**Container's getter for MoissPInfoVO7
     */
    public MoissPInfoVOImpl getMoissPInfoVO7() {
        return (MoissPInfoVOImpl)findViewObject("MoissPInfoVO7");
    }

    /**Container's getter for MoissPInfoVO8
     */
    public MoissPInfoVOImpl getMoissPInfoVO8() {
        return (MoissPInfoVOImpl)findViewObject("MoissPInfoVO8");
    }

    /**Container's getter for popPunchLOVVO
     */
    public popPunchLOVVOImpl getpopPunchLOVVO() {
        return (popPunchLOVVOImpl)findViewObject("popPunchLOVVO");
    }

    /**Container's getter for MoissPIVO
     */
    public MoissPIVOImpl getMoissPIVO() {
        return (MoissPIVOImpl)findViewObject("MoissPIVO");
    }

    /**Container's getter for MoissTempVO
     */
    public MoissTempVOImpl getMoissTempVO() {
        return (MoissTempVOImpl)findViewObject("MoissTempVO");
    }
}
