package moiss.oracle.apps.fnd.moiss.server;

import moiss.oracle.apps.fnd.moiss.schema.server.MoissPIEOImpl;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MoissPIVORowImpl extends OAViewRowImpl {
    public static final int ROWID1 = 0;
    public static final int PUNCHINFOID = 1;
    public static final int PUNCHCODE = 2;
    public static final int PUNCHCODEDESC = 3;
    public static final int EMPLOYEENUMBER = 4;
    public static final int EMPLOYEENAME = 5;
    public static final int PUNCHDATE = 6;
    public static final int STATE = 7;
    public static final int NEWSTATE = 8;
    public static final int EXCEPTION = 9;
    public static final int DEPARTMENT = 10;
    public static final int MANENTRYYN = 11;
    public static final int REMARKS = 12;
    public static final int ATTRIBUTECATEGORY = 13;
    public static final int ATTRIBUTE1 = 14;
    public static final int ATTRIBUTE2 = 15;
    public static final int ATTRIBUTE3 = 16;
    public static final int ATTRIBUTE4 = 17;
    public static final int ATTRIBUTE5 = 18;
    public static final int ATTRIBUTE6 = 19;
    public static final int ATTRIBUTE7 = 20;
    public static final int ATTRIBUTE8 = 21;
    public static final int ATTRIBUTE9 = 22;
    public static final int ATTRIBUTE10 = 23;
    public static final int CREATEDBY = 24;
    public static final int CREATIONDATE = 25;
    public static final int LASTUPDATEDBY = 26;
    public static final int LASTUPDATEDATE = 27;
    public static final int LASTUPDATELOGIN = 28;

    /**This is the default constructor (do not remove)
     */
    public MoissPIVORowImpl() {
    }

    /**Gets MoissPIEO entity object.
     */
    public MoissPIEOImpl getMoissPIEO() {
        return (MoissPIEOImpl)getEntity(0);
    }

    /**Gets the attribute value for the calculated attribute RowId1
     */
    public RowID getRowId1() {
        return (RowID) getAttributeInternal(ROWID1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RowId1
     */
    public void setRowId1(RowID value) {
        setAttributeInternal(ROWID1, value);
    }

    /**Gets the attribute value for PUNCH_INFO_ID using the alias name PunchInfoId
     */
    public Number getPunchInfoId() {
        return (Number) getAttributeInternal(PUNCHINFOID);
    }

    /**Sets <code>value</code> as attribute value for PUNCH_INFO_ID using the alias name PunchInfoId
     */
    public void setPunchInfoId(Number value) {
        setAttributeInternal(PUNCHINFOID, value);
    }

    /**Gets the attribute value for PUNCH_CODE using the alias name PunchCode
     */
    public String getPunchCode() {
        return (String) getAttributeInternal(PUNCHCODE);
    }

    /**Sets <code>value</code> as attribute value for PUNCH_CODE using the alias name PunchCode
     */
    public void setPunchCode(String value) {
        setAttributeInternal(PUNCHCODE, value);
    }

    /**Gets the attribute value for the calculated attribute PunchCodeDesc
     */
    public String getPunchCodeDesc() {
        return (String) getAttributeInternal(PUNCHCODEDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PunchCodeDesc
     */
    public void setPunchCodeDesc(String value) {
        setAttributeInternal(PUNCHCODEDESC, value);
    }

    /**Gets the attribute value for EMPLOYEE_NUMBER using the alias name EmployeeNumber
     */
    public Number getEmployeeNumber() {
        return (Number) getAttributeInternal(EMPLOYEENUMBER);
    }

    /**Sets <code>value</code> as attribute value for EMPLOYEE_NUMBER using the alias name EmployeeNumber
     */
    public void setEmployeeNumber(Number value) {
        setAttributeInternal(EMPLOYEENUMBER, value);
    }

    /**Gets the attribute value for EMPLOYEE_NAME using the alias name EmployeeName
     */
    public String getEmployeeName() {
        return (String) getAttributeInternal(EMPLOYEENAME);
    }

    /**Sets <code>value</code> as attribute value for EMPLOYEE_NAME using the alias name EmployeeName
     */
    public void setEmployeeName(String value) {
        setAttributeInternal(EMPLOYEENAME, value);
    }

    /**Gets the attribute value for PUNCH_DATE using the alias name PunchDate
     */
    public String getPunchDate() {
        return (String) getAttributeInternal(PUNCHDATE);
    }

    /**Sets <code>value</code> as attribute value for PUNCH_DATE using the alias name PunchDate
     */
    public void setPunchDate(String value) {
        setAttributeInternal(PUNCHDATE, value);
    }

    /**Gets the attribute value for STATE using the alias name State
     */
    public String getState() {
        return (String) getAttributeInternal(STATE);
    }

    /**Sets <code>value</code> as attribute value for STATE using the alias name State
     */
    public void setState(String value) {
        setAttributeInternal(STATE, value);
    }

    /**Gets the attribute value for NEW_STATE using the alias name NewState
     */
    public String getNewState() {
        return (String) getAttributeInternal(NEWSTATE);
    }

    /**Sets <code>value</code> as attribute value for NEW_STATE using the alias name NewState
     */
    public void setNewState(String value) {
        setAttributeInternal(NEWSTATE, value);
    }

    /**Gets the attribute value for EXCEPTION using the alias name Exception
     */
    public String getException() {
        return (String) getAttributeInternal(EXCEPTION);
    }

    /**Sets <code>value</code> as attribute value for EXCEPTION using the alias name Exception
     */
    public void setException(String value) {
        setAttributeInternal(EXCEPTION, value);
    }

    /**Gets the attribute value for DEPARTMENT using the alias name Department
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**Sets <code>value</code> as attribute value for DEPARTMENT using the alias name Department
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**Gets the attribute value for MAN_ENTRY_YN using the alias name ManEntryYn
     */
    public String getManEntryYn() {
        return (String) getAttributeInternal(MANENTRYYN);
    }

    /**Sets <code>value</code> as attribute value for MAN_ENTRY_YN using the alias name ManEntryYn
     */
    public void setManEntryYn(String value) {
        setAttributeInternal(MANENTRYYN, value);
    }

    /**Gets the attribute value for REMARKS using the alias name Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            return getRowId1();
        case PUNCHINFOID:
            return getPunchInfoId();
        case PUNCHCODE:
            return getPunchCode();
        case PUNCHCODEDESC:
            return getPunchCodeDesc();
        case EMPLOYEENUMBER:
            return getEmployeeNumber();
        case EMPLOYEENAME:
            return getEmployeeName();
        case PUNCHDATE:
            return getPunchDate();
        case STATE:
            return getState();
        case NEWSTATE:
            return getNewState();
        case EXCEPTION:
            return getException();
        case DEPARTMENT:
            return getDepartment();
        case MANENTRYYN:
            return getManEntryYn();
        case REMARKS:
            return getRemarks();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            setRowId1((RowID)value);
            return;
        case PUNCHINFOID:
            setPunchInfoId((Number)value);
            return;
        case PUNCHCODE:
            setPunchCode((String)value);
            return;
        case PUNCHCODEDESC:
            setPunchCodeDesc((String)value);
            return;
        case EMPLOYEENUMBER:
            setEmployeeNumber((Number)value);
            return;
        case EMPLOYEENAME:
            setEmployeeName((String)value);
            return;
        case PUNCHDATE:
            setPunchDate((String)value);
            return;
        case STATE:
            setState((String)value);
            return;
        case NEWSTATE:
            setNewState((String)value);
            return;
        case EXCEPTION:
            setException((String)value);
            return;
        case DEPARTMENT:
            setDepartment((String)value);
            return;
        case MANENTRYYN:
            setManEntryYn((String)value);
            return;
        case REMARKS:
            setRemarks((String)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
