package moiss.oracle.apps.moiss.doclib.server;

import java.io.Serializable;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocLibUserVOImpl extends OAViewObjectImpl implements Serializable {
    /**This is the default constructor (do not remove)
     */
    public DocLibUserVOImpl() {
    }
}
