package moiss.oracle.apps.moiss.doclib.server;

import moiss.oracle.apps.moiss.doclib.schema.server.DocLibEOImpl;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocLibVORowImpl extends OAViewRowImpl {
    public static final int ROWID1 = 0;
    public static final int DOCID = 1;
    public static final int DOCUMENTNAME = 2;
    public static final int DOCUMENTFILE = 3;
    public static final int OWNINGDEPT = 4;
    public static final int OWNINGDEPTDESC = 5;
    public static final int CATEGORY = 6;
    public static final int CATEGORYDESC = 7;
    public static final int DOCUMENTNUMBER = 8;
    public static final int VERSIONNUMBER = 9;
    public static final int EFFECTIVESTARTDATE = 10;
    public static final int EFFECTIVEENDDATE = 11;
    public static final int MUSTREAD = 12;
    public static final int ATTRIBUTECATEGORY = 13;
    public static final int ATTRIBUTE1 = 14;
    public static final int ATTRIBUTE2 = 15;
    public static final int ATTRIBUTE3 = 16;
    public static final int ATTRIBUTE4 = 17;
    public static final int ATTRIBUTE5 = 18;
    public static final int ATTRIBUTE6 = 19;
    public static final int ATTRIBUTE7 = 20;
    public static final int ATTRIBUTE8 = 21;
    public static final int ATTRIBUTE9 = 22;
    public static final int ATTRIBUTE10 = 23;
    public static final int CREATEDBY = 24;
    public static final int CREATIONDATE = 25;
    public static final int LASTUPDATEDBY = 26;
    public static final int LASTUPDATEDATE = 27;
    public static final int LASTUPDATELOGIN = 28;

    /**This is the default constructor (do not remove)
     */
    public DocLibVORowImpl() {
    }

    /**Gets DocLibEO entity object.
     */
    public DocLibEOImpl getDocLibEO() {
        return (DocLibEOImpl)getEntity(0);
    }

    /**Gets the attribute value for the calculated attribute RowId1
     */
    public RowID getRowId1() {
        return (RowID) getAttributeInternal(ROWID1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RowId1
     */
    public void setRowId1(RowID value) {
        setAttributeInternal(ROWID1, value);
    }

    /**Gets the attribute value for DOC_ID using the alias name DocId
     */
    public Number getDocId() {
        return (Number) getAttributeInternal(DOCID);
    }

    /**Sets <code>value</code> as attribute value for DOC_ID using the alias name DocId
     */
    public void setDocId(Number value) {
        setAttributeInternal(DOCID, value);
    }

    /**Gets the attribute value for DOCUMENT_NAME using the alias name DocumentName
     */
    public String getDocumentName() {
        return (String) getAttributeInternal(DOCUMENTNAME);
    }

    /**Sets <code>value</code> as attribute value for DOCUMENT_NAME using the alias name DocumentName
     */
    public void setDocumentName(String value) {
        setAttributeInternal(DOCUMENTNAME, value);
    }

    /**Gets the attribute value for DOCUMENT_FILE using the alias name DocumentFile
     */
    public BlobDomain getDocumentFile() {
        return (BlobDomain) getAttributeInternal(DOCUMENTFILE);
    }

    /**Sets <code>value</code> as attribute value for DOCUMENT_FILE using the alias name DocumentFile
     */
    public void setDocumentFile(BlobDomain value) {
        setAttributeInternal(DOCUMENTFILE, value);
    }

    /**Gets the attribute value for OWNING_DEPT using the alias name OwningDept
     */
    public String getOwningDept() {
        return (String) getAttributeInternal(OWNINGDEPT);
    }

    /**Sets <code>value</code> as attribute value for OWNING_DEPT using the alias name OwningDept
     */
    public void setOwningDept(String value) {
        setAttributeInternal(OWNINGDEPT, value);
    }

    /**Gets the attribute value for the calculated attribute OwningDeptDesc
     */
    public String getOwningDeptDesc() {
        return (String) getAttributeInternal(OWNINGDEPTDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OwningDeptDesc
     */
    public void setOwningDeptDesc(String value) {
        setAttributeInternal(OWNINGDEPTDESC, value);
    }

    /**Gets the attribute value for CATEGORY using the alias name Category
     */
    public String getCategory() {
        return (String) getAttributeInternal(CATEGORY);
    }

    /**Sets <code>value</code> as attribute value for CATEGORY using the alias name Category
     */
    public void setCategory(String value) {
        setAttributeInternal(CATEGORY, value);
    }

    /**Gets the attribute value for the calculated attribute CategoryDesc
     */
    public String getCategoryDesc() {
        return (String) getAttributeInternal(CATEGORYDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CategoryDesc
     */
    public void setCategoryDesc(String value) {
        setAttributeInternal(CATEGORYDESC, value);
    }

    /**Gets the attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber
     */
    public String getDocumentNumber() {
        return (String) getAttributeInternal(DOCUMENTNUMBER);
    }

    /**Sets <code>value</code> as attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber
     */
    public void setDocumentNumber(String value) {
        setAttributeInternal(DOCUMENTNUMBER, value);
    }

    /**Gets the attribute value for VERSION_NUMBER using the alias name VersionNumber
     */
    public String getVersionNumber() {
        return (String) getAttributeInternal(VERSIONNUMBER);
    }

    /**Sets <code>value</code> as attribute value for VERSION_NUMBER using the alias name VersionNumber
     */
    public void setVersionNumber(String value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**Gets the attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**Sets <code>value</code> as attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**Gets the attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**Sets <code>value</code> as attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**Gets the attribute value for MUST_READ using the alias name MustRead
     */
    public String getMustRead() {
        return (String) getAttributeInternal(MUSTREAD);
    }

    /**Sets <code>value</code> as attribute value for MUST_READ using the alias name MustRead
     */
    public void setMustRead(String value) {
        setAttributeInternal(MUSTREAD, value);
    }

    /**Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            return getRowId1();
        case DOCID:
            return getDocId();
        case DOCUMENTNAME:
            return getDocumentName();
        case DOCUMENTFILE:
            return getDocumentFile();
        case OWNINGDEPT:
            return getOwningDept();
        case OWNINGDEPTDESC:
            return getOwningDeptDesc();
        case CATEGORY:
            return getCategory();
        case CATEGORYDESC:
            return getCategoryDesc();
        case DOCUMENTNUMBER:
            return getDocumentNumber();
        case VERSIONNUMBER:
            return getVersionNumber();
        case EFFECTIVESTARTDATE:
            return getEffectiveStartDate();
        case EFFECTIVEENDDATE:
            return getEffectiveEndDate();
        case MUSTREAD:
            return getMustRead();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ROWID1:
            setRowId1((RowID)value);
            return;
        case DOCID:
            setDocId((Number)value);
            return;
        case DOCUMENTNAME:
            setDocumentName((String)value);
            return;
        case DOCUMENTFILE:
            setDocumentFile((BlobDomain)value);
            return;
        case OWNINGDEPT:
            setOwningDept((String)value);
            return;
        case OWNINGDEPTDESC:
            setOwningDeptDesc((String)value);
            return;
        case CATEGORY:
            setCategory((String)value);
            return;
        case CATEGORYDESC:
            setCategoryDesc((String)value);
            return;
        case DOCUMENTNUMBER:
            setDocumentNumber((String)value);
            return;
        case VERSIONNUMBER:
            setVersionNumber((String)value);
            return;
        case EFFECTIVESTARTDATE:
            setEffectiveStartDate((Date)value);
            return;
        case EFFECTIVEENDDATE:
            setEffectiveEndDate((Date)value);
            return;
        case MUSTREAD:
            setMustRead((String)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
